language: python
dist: trusty
sudo: required
matrix:
  include:
  - os: linux
    dist: trusty
    python: 2.7
  - os: linux
    dist: trusty
    python: 3.5
  - os: linux
    dist: trusty
    python: 3.6
  - os: linux
    dist: trusty
    python: pypy
  - os: linux
    dist: trusty
    python: pypy3.5
  - os: linux
    dist: xenial
    python: 3.7
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install_python.sh; fi
install: 'pip install -r requirements.txt; pip install pytest-rerunfailures '
script: pytest --reruns 5 -v zopyx
env:
  global:
  - secure: AorqFYU9y6J07ECP4UVRfGsqAVq+HYaLeNk0y7t/dvobkeY2ymPFifPfbTF3zHndWQFWeORtu7b5mFCNQrwI64W56jbuPtuSNF3bha7Q6IKYVkY9yMhvaHZMy9ZcD2S0Q51IFNd1QrbOuWC4HFq0CDKQn7uKEScad/xz4T9MSu0TEn6h24cgsnlJHMiNNUG08JrMSjag1+9/YV/sz9YHUxJbGE4mUpYf7PcNvZ2d0VvKYxaFzqxyRjY9OYJtyKKaVGBmMZb+owaDmEv68L/e9B3BAyJgtYzsDT4AE5D8ZjrKsG31bPSq21ow6ipuoCZdgHAR2VZzlerIaBh5MNIQQDMkl4w2/hEiTDm4vrzO5ElzBASZz+Iuc6nfdXpCQ9+yvGyqv8KHai8lACV/5RcQcy0YH0fwakjHZ1fTvU8nCLDgRb2n0cFkN1TbwY/VBFskxxTwb8kJKJd+fe41msjCqmziTTtfPqQXAUSF7wE5gT/ewMvLQ+Hdp9TzDpOArLskIZ7yOON7HN3UEcsU41YAjdoygBr7nAbJb+Okjf7zp2Y7RnLTi6PVodbqAk6SEg12UOrb7e1bsXNSiQT07MAjaUOI5En8fYCUzS1LwjhaMzFBXB0PumAv9zAkUUx2/QfA6zLFjuLjjxLZFLN5QoraSKswKj4Jv0X73GpGi2VyZ5A=
  - secure: s5T9Q4CllzxwlpyeJU/wmb4VC4akRKg5ivFkZVNMxqRwfisQLFoHQFUK4a/CAB4YsfKkXb0CXUsOUTfJVigaNC1M9Xou9SIeaRdvSCHRDzfAXl+UMeEVjPF35wgQ0EqW3ALngl7pvVR34Kf5kHTPtX1MWhl1iX+uRgYTd5lCfaOeMOmqmLFl0EugQjkYwiOHtb2uqRkdGv4KuJUqWDyU4YwyqFpGoTgLtUw54e0f4aDatOoQyY3RMwjlQlyaAX+Y7WftLGeYu50qOqFoVjbAnbAOHx3Tz1uyum7D04tFW8X/30B6IeC+yL/Rl/gT58a1TPme/whaFcacUA60+j8fvYg5AR5IYg52fCLG9rx5Hef1l8vD/NHEMA+87eUlGD34bovwnZBxEj1SC5JnLjI/1U5JWZ2HO7OxNVSxNgnml0BS3PGfZZ0sjr+ZkzMWFUktQ6XP9j1mrt180j2wMFUzywBhGYVJYJDoA+h4wHn3Ao9VR7EgU1tntodbyXTUiMB7dB4jeI6UyPb70978zmZLYVrIW7NhaYpfCftVimdjhx00LjJqBX+h4RYYw+PQjXpOGCuw0t/Zbh7wM/4EgsvxyPZsxLMX0trYCkAJUjig/V13sulDVXVrvwe3kXMWHP22Yj4xznvLkgQy73JZd+34bHFx6LP6EdC4KnN7my1iSNI=
  - secure: No//CvDqup7uNdYn/79GRI1vGqpQxfl4CfOeADtum4eYmPEXjr20TrQzF98UoRC6qZRtA0zYZzCsjjABituV4mtDvGKE6ZHovGQpIxiAjIMPv4KYh7053+2M1Z0s3SnTbedGyDSN/tzaXhB1uituT1L37Mx+zEkRExjHBxytKz322YTfj0BkS1A/t/QVDBaTSxIxvvBLRqo6Nt7T8GRhj0agqoGYclsDxkivl6l3bDG2uiUWJjURy4FVGM4LI+qzqUQ8FneHmYLyLIk+1O1h1vCVSBGIXCVRz9LkpPnFztIYv0Dlaj8VmYSSmK2hUeT0Qui3sMC23oYJx4y9gct1QmQAQ3Qi2C9zRuzFf7PKvVShqIwV4lNvM0d0wRg2yyQOo9zhfDvtF0OTBKORnWr114iAx6CXyq7kRsgM1LNhXGANRjSNEwPGkTyy0BTIcrkRlY8GaQS2qW6yNNnHJT8FN6pfkb8F8hfwGneTPkkvwNBnwWyuW5d5rIGOTr44q3wrAlPu7c2MEFo3+hqf7fr5OXSqrFvo4ktT2hiHKzFK0BeqFGR6wYmnOKwJKJjcKrvduFctwBkJ8OdvsmdJiK3WGf/AyXefQlkl1npqKw9Vnt5aNTw230S33hVnTZYUr874n792v8fotYUo/pFm67cXXj6jrgqu8xu8vuR1SqhjK2M=
