language: python
dist: trusty
sudo: required
matrix:
  include:
  - os: linux
    dist: trusty
    python: 2.7
  - os: linux
    dist: trusty
    python: 3.5
  - os: linux
    dist: trusty
    python: 3.6
  - os: linux
    dist: trusty
    python: pypy
  - os: linux
    dist: trusty
    python: pypy3.5
  - os: linux
    dist: xenial
    python: 3.7
  - os: linux
    dist: xenial
    python: 3.8-dev
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install_python.sh; fi
install: 'pip install -r requirements.txt; pip install pytest-rerunfailures '
script: pytest --reruns 5 -v zopyx
env:
  global:
  - secure: dGOHB4rbGfpyv0y8a1TJKZMBR4c/AmcGk1SRoz/E08khaZUhUsUiZG4zHPI7wQb/MZtwmlBgeNH/qk/eCDD0bKBgG+7dL75/uAAdg55Typ4Y98pA/5oD325bwf1eY59uc4J44JLm4KkH7NtOHyEQYb/UB4iiwoq1oUQXc8bcGgYqbyLyShWpYzEso3nBdA+rLRmM5oiWEGumMwf+dRLlLz26KxngVUvK8RpClG+R15Xdp3k+1wbL8GzWc5V1zlnlV+f+32zwKlk1csbRzNEmefVpfk/ukTCvLUvCS3TFANR+OqhCNbmhhPCmLNnVdaV64gRQkO4W3gnuLbep/SXNh1aYzInMNsT4JhUJOUwXeJfqYDA9mdAs9kWplGEkzZJiXa9RGxWQu3WoPTsDOcZ0b5wFz50IsOEMoBVzOTDXZvn1iIY4lSyHn13RqtPTOVMiknaqzQ+p/RoumFK0jvKd6SdYywzmMdPdodcS5FNgPKSKBjUfmMHavzQmjiDpqq90j+3i9qMIUxcRyTRdf3MVmiq1xApknPZGtyqgLLtg24sRDd9bP1eUDKHz6OmrZBbtXlsbubeHn5xMRy1eAS8i33PhbcRJFXlHoAOuQXfyY8wc0/4s6pmEaLAH/HFEgnGi0T3t945SPSUNkKBM0yi5diR8Z7OPmjcJ/4QSEa7HMg8=
  - secure: jMJdQ6mLwjMSbjkvdH6DqzVwDNX+Lu1TIhuQHcOcgV+q95Ip7xEaTKQ5WKCyXcMIPBTN8u6EwVIK3rHKjfKtFscQCT5TYwZhAHrvnuMZ1hFHmGZOhrIGh6/eD7Dk2lrS2ApRB95g/ktOy3qx042+1LMag1diRWp0sTWvk8x+2vUD5nNFXlXMPkrg22WvJAgDuFpPAzZ76KBJDLgQ6Y4y8XWIEjWhPrftTSU9tLQztX36EFIXaUCduhBRkpi6RzOhG17f08OVTyfyXvPL4uYuhAwyMsSE998w0bvJxJIm9ZN0AkLuz5maygA4qvXd8/w4REaTvUGfmFwE5UY8L/tq1sF0Cs+XYc283Jx4ljxhT+ZaXWQ9q+bqkIpW88XllU4YDOM0QnbMH7+Tms7lbVWfFvgTl3Oyfmmn6ep3V2c+2PXSwGIEmi76+bd36EMNppmYGpIXoL2mPFuCl++avq7xsx2gHI403h84mamsOWy71AmpNnWeMV5YnWX/Z6eFNt5UMOsONpQlZRma2YQeKve4zTK7aD19zeMw0BVJJd7gAJrMN3ncCpDecHXDY+g4TwRYEfnodACNQlyVAra9hGXsIuyTLNzNxxK4ouBvylALmwCDp9GZkyD3Zkouv9mu/lTVu2m7Fb5AaqjBdMZE+Jd+poPM8yXr65UECBp0HFz2lYs=
  - secure: DfMea7vu1cYItQR7rBHCzTUf6V8UBZhA4JY5q4IKyhbkxPcdOkVlh79o2cBlP/9sVqEID8Mu7KoAg5m6Iiyh6+Wc+Tpt5DOsarXV/1GOMpykjUnVg/+lKN5qHg6HTp5IHpMcBmQTwxqogDpO480XxiKwgK2yK10yKnmQM3KV5oy8ePm9GJaVnIllrkQvp/kTcMLet2tKcVh/63IuM5O35tj5SvJBt5+ElAtKop8t2j+ICW7pH1gW3Gc3Q4/zmTvMaqelKFsvTrDwO8ky7mj4mp0K4mDrCgXGsnfF/a1/3EGuSgoj5Km3I/0UO7YpwErU/2Z7GBc/UoIlzKOJMia8X/0hcVNI+u0BKFe5pfhgCdvu9E28GwP4TMYcGL71Er2LprhA+dizy5xyrWVjtJmvCiuF1f+4GCiF8m2pu2SvtBmMLP3ZEWjEQosBERMBKlI5bd5WesjE0guUhdvw8eHRxj7rLwAXDnQeur9UcB45kKlogxd08oc1vpdccikuSoYQmtRGLyoDsj20+8dC7Iakpas5WbhG+EPXdPYTCRAH24fXER5/P4Q27VlsxZXiavVN0j62thzKBFhqledPr0YP5OnjlRGwR3VmsiqXKCkOcd44DMH1bwkPjDkOjD+hA+hcr6TA9TRK+WUkoMS8M/gnjUZFLgEJ1HvgoAkpKoqOXIQ=
