language: python
dist: trusty
sudo: required
matrix:
  include:
  - os: linux
    dist: trusty
    python: 2.7
  - os: linux
    dist: trusty
    python: 3.5
  - os: linux
    dist: trusty
    python: 3.6
  - os: linux
    dist: trusty
    python: pypy
  - os: linux
    dist: trusty
    python: pypy3.5
  - os: linux
    dist: xenial
    python: 3.7
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install_python.sh; fi
install: 'pip install -r requirements.txt; pip install pytest-rerunfailures '
script: pytest --reruns 5 -v zopyx
env:
  global:
  - secure: GhwxVzx6HPaUNzGKRH3se1cLEm64R6tc+5d5kOcja/2IfJl/sR4enifQmqHzBCJBlkny4XsZNeqCtPA57yJdKYTF52iJ+W/BmTcEPfY20eitDUlN4amimCzbSSSZBns65CNm0IAkyzZ0/0jEDhv3hDlZANphaA5uRVrik1J80PDMTn+PhWWL5gvP36f+GAymBnk4FMYDbsenhi1MMIh2vBDkFQYQT3QTmI0TpSktRfXALd0kwoYDB256BvLTwK8LxiNCmF7IKUUT+8p5kfrcRoC65kxaJn3PKv3Yrtdq+zlwOj24e3XkS6pKhJbhJVmPmOldynUPTuA7KKT+os3iBizdSaeqDQ3N+KDJCk7bZgYx1IzeXh4xPJM2PYOtMl2oJe6S75+q12HRbY7A/xWGmq0SPYM0iqw+Y4c+Otilc/AbYbVzjQXw86Yfe/blNO5YXxffchxJvMOLyRmh04PaB2l2yGuE1UQlGycZfxCx0aP4YvLcupfSBYk21ypZuYs6MbER2Fpgx3tGbtncSeD7hvkCoNieChiMmTc8J+us54eH7y0T64ENYg437AlJDVIXavpJ3teqSqoIzYozf9nmQl6yDI139GExuKe8OjxyY/9SahizscM4K+TIsNgF2CAQF7RE8hdbIHvZ+cTj+FaKsH18hEzd3Tc30Jd/CVs8Knc=
  - secure: uXQLvwn7ZQdFqrAub/Em4TFitWA6IUJFhJagisk2zkkiwFhuWEYoRWPK1UKBMUeSKqpMSHKT23dkwi8k5xwYtQWmQ5GXggo8SxS8/vMWS1vNK3mSevxGQxRy1iggT93TlJ4cm1tJ/aRKCR9/pt56KBpgrOrpZKZSaAy5jTGw7gdHBYsx7VRByCl2oMi+kZeRmkwXu1HG8q8lerKb01ZL+0PngF06yk+iwlkFXuDjdyTpLy1qWuUFrvrbaEcb8zJcEEpoONaI2FADBl2UT0zuyDGkJeb2dfWdIeALAGxTELCmIqD5lvG0qPi9cpqnz13QrQc2cWwkpcsAzYxAAONoFKqc3k17Lxq95a17MYB4LJ9XvJlY/DpZF/DpZ3QFUnNo7SEr1zkrmdhI1glbBAe9ZCfbq3SR2TP2WL7Rol2f3GcmSXpW7Ld1idH+4R1zAdqvBHCz2HsXYZQRr6f8+NBmyQYItexfMBxVe7W6wA6OusjnQBTm1n3/7KFTCEAI/PFQ0mdVoUfTK6dCpCdrMYRT1PDt5QakIQeySlg4ogmUcFzjoUbnx6GZDcYN5n0HwDsQPrmUFKbMFw+4qTeCvhajYO5ZaDQEUPRUxgBbsVzBOGuJZZ6IMfOgl5sk48jMK8YFrCgFdgStaiR4nllHY54lirW96i43bbS8kdBIFAB1dbo=
  - secure: P1uU3AkC3r6jdS2jysCgPq7her21aEZDENw8Mkv1xB7fKwBr+4VfJJO5+3I7dFnb4a1XueeDdtJMaCpvFMJos4iDn31QjbchUE5qpL45E1xebx1x4UycLdJw1jsKWoGIqZ9Z8niLAmOw0GQ5fPcbqSc+F1hVffGupBSWhggG9bBXoAKd3DZiW4wGNQ/dVohoLPQ/7H01kpBMDqUKCLuPtwBAvrawfZ6YwJF/6RIPgKfQrSnUgDAwYWV6nERnb7z/rkG880J0w1e+J+Rpeyb/1E+zl6KTpg7q3KsOVHW7WF4amiFxm2sx0cxboOHxiLDDcrXwnc1c8Ram/xCogyudxG4y98oXCvKMDailBBuYrWU+ynFBVfFRbu/V3tG7HMteK+hPWllZA2i7qjZ63KR/EUN9U9Hqx6YFnwD9F/2FDGPt0l5Xng9q2fAB8puXWcaA6PZE5pLYTYsGs4pTpOj9Uz2gk8clX0K2kzo476jg2noYqMrcdZANMtOXUhnJJhGmOup0OGU/rsuY/Fx6D1161z64cr1lG0fCzM3ucrqy7WuZNSotBAIZ2CazmQY7yBBaalj+4SL+jExnGC1c5CII3oijfYESO2iERgIgmAyMVmF22IlxErtYoBWh/a6JTeXw1JZYsbtJA08YODWxpmoFIvXfnjdbnBVxokkrpI83NO0=
