language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: make install
script: make test
env:
  global:
    secure: OCATJcs9LhfzqdvYd0E5MWtLHjG1iNLZ7TW4tM37IOwzhi8azqkTJglfLinysmlGpx69nrXwdyj/kkd3/yjBhKMa/rJWdxYNMwHqeWyShNXKinhi1duZUdDfts9ESVr2jI/jI19FNOt/41gw1epBKWUhwZbUToMC9oGNFjvQseAcGjDUKvkh2GFn1W9pQx5Qfc64S1n+40geoktB+PxV/DRtWFzWiME82V7udKcUWck4LeUj+OGKYFRjaSUsT65Kc/S9qHBy2j/0GSQkDR3W8QuDEqBY59pWnASdkIfot0agvmoJ++Cni51Olhck12rOnBK6h2yjJWKN1YxQ0W5iOQ3T9Ancun4MgkcdEe54j2LrmTSjTf/mgf+KeVEuy24MefOwdnT49CgmWX/USUKbBz7qaTMyMDAEmMggFgiEg2DNvQoGMXs+JMEqEHii3iaNKEWmFkig7jw4SIUQStW2x0b1nwDR4Ojc1qHJ6jNQPlYHzEdwuzxV9jiVguCy3mR1YfFmgqXOYz7mi5grCGRsDcVFzm0FN4gqc6mc38TWPTxESJNf7Wnifn6SAFOG373+MZ263F7cN6nF6p3LlGU7b/h0Apirx1ZwcGB/AAfgYXXwOQxAtKe0wiVC0ayIVW+tUx5SURV+QAGRJWw0UJaAx0gvEu6sSOmF/DlKVELA3vc=
